-- Converted using Mokiros's Model to Script Version 3
-- Converted string size: 32288 characters

local ScriptFunctions = {
function(script,require)
while true do
	wait(0.1)
	script.Parent.TextureID = "rbxassetid://667900559"
	wait(5)
	script.Parent.TextureID = "http://www.roblox.com/asset/?id=673679186"
	wait(0.1)
	script.Parent.TextureID = "http://www.roblox.com/asset/?id=673679187"
	wait(0.1)
	script.Parent.TextureID = "http://www.roblox.com/asset/?id=673679186"
end

end
}
local ScriptIndex = 0
local Scripts,ModuleScripts,ModuleCache = {},{},{}
local _require = require
function require(obj,...)
	local index = ModuleScripts[obj]
	if not index then
		local a,b = pcall(_require,obj,...)
		return not a and error(b,2) or b
	end
	
	local res = ModuleCache[index]
	if res then return res end
	res = ScriptFunctions[index](obj,require)
	if res==nil then error("Module code did not return exactly one value",2) end
	ModuleCache[index] = res
	return res
end
local function Script(obj,ismodule)
	ScriptIndex = ScriptIndex + 1
	local t = ismodule and ModuleScripts or Scripts
	t[obj] = ScriptIndex
end

function RunScripts()
	for script,index in pairs(Scripts) do
		coroutine.wrap(ScriptFunctions[index])(script,require)
	end
end


local function DecodeUnion(Values,Flags,Parse,data)
	local m = Instance.new("Folder")
	m.Name = "UnionCache ["..tostring(math.random(1,9999)).."]"
	m.Archivable = false
	m.Parent = game:GetService("ServerStorage")
	local Union,Subtract = {},{}
	if not data then
		data = Parse('B')
	end
	local ByteLength = (data % 4) + 1
	local Length = Parse('I'..ByteLength)
	local ValueFMT = ('I'..Flags[1])
	for i = 1,Length do
		local data = Parse('B')
		local part
		local isNegate = bit32.band(data,0b10000000) > 0
		local isUnion =  bit32.band(data,0b01000000) > 0
		if isUnion then
			part = DecodeUnion(Values,Flags,Parse,data)
		else
			local isMesh = data % 2 == 1
			local ClassName = Values[Parse(ValueFMT)]
			part = Instance.new(ClassName)
			part.Size = Values[Parse(ValueFMT)]
			part.Position = Values[Parse(ValueFMT)]
			part.Orientation = Values[Parse(ValueFMT)]
			if isMesh then
				local mesh = Instance.new("SpecialMesh")
				mesh.MeshType = Values[Parse(ValueFMT)]
				mesh.Scale = Values[Parse(ValueFMT)]
				mesh.Offset = Values[Parse(ValueFMT)]
				mesh.Parent = part
			end
		end
		part.Parent = m
		table.insert(isNegate and Subtract or Union,part)
	end
	local first = table.remove(Union,1)
	if #Union>0 then
		first = first:UnionAsync(Union)
	end
	if #Subtract>0 then
		first = first:SubtractAsync(Subtract)
	end
	m:Destroy()
	return first
end

local function Decode(str)
	local StringLength = #str
	
	-- Base64 decoding
	do
		local decoder = {}
		for b64code, char in pairs(('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='):split('')) do
			decoder[char:byte()] = b64code-1
		end
		local n = StringLength
		local t,k = table.create(math.floor(n/4)+1),1
		local padding = str:sub(-2) == '==' and 2 or str:sub(-1) == '=' and 1 or 0
		for i = 1, padding > 0 and n-4 or n, 4 do
			local a, b, c, d = str:byte(i,i+3)
			local v = decoder[a]*0x40000 + decoder[b]*0x1000 + decoder[c]*0x40 + decoder[d]
			t[k] = string.char(bit32.extract(v,16,8),bit32.extract(v,8,8),bit32.extract(v,0,8))
			k = k + 1
		end
		if padding == 1 then
			local a, b, c = str:byte(n-3,n-1)
			local v = decoder[a]*0x40000 + decoder[b]*0x1000 + decoder[c]*0x40
			t[k] = string.char(bit32.extract(v,16,8),bit32.extract(v,8,8))
		elseif padding == 2 then
			local a, b = str:byte(n-3,n-2)
			local v = decoder[a]*0x40000 + decoder[b]*0x1000
			t[k] = string.char(bit32.extract(v,16,8))
		end
		str = table.concat(t)
	end
	
	local Position = 1
	local function Parse(fmt)
		local Values = {string.unpack(fmt,str,Position)}
		Position = table.remove(Values)
		return table.unpack(Values)
	end
	
	local Settings = Parse('B')
	local Flags = Parse('B')
	Flags = {
		--[[ValueIndexByteLength]] bit32.extract(Flags,6,2)+1,
		--[[InstanceIndexByteLength]] bit32.extract(Flags,4,2)+1,
		--[[ConnectionsIndexByteLength]] bit32.extract(Flags,2,2)+1,
		--[[MaxPropertiesLengthByteLength]] bit32.extract(Flags,0,2)+1,
		--[[Use Double instead of Float]] bit32.band(Settings,0b1) > 0
	}
	
	local ValueFMT = ('I'..Flags[1])
	local InstanceFMT = ('I'..Flags[2])
	local ConnectionFMT = ('I'..Flags[3])
	local PropertyLengthFMT = ('I'..Flags[4])
	
	local ValuesLength = Parse(ValueFMT)
	local Values = table.create(ValuesLength)
	local CFrameIndexes = {}
	
	local ValueDecoders = {
		--!!Start
		[1] = function(Modifier)
			return Parse('s'..Modifier)
		end,
		--!!Split
		[2] = function(Modifier)
			return Modifier ~= 0
		end,
		--!!Split
		[3] = function()
			return Parse('d')
		end,
		--!!Split
		[4] = function(_,Index)
			table.insert(CFrameIndexes,{Index,Parse(('I'..Flags[1]):rep(3))})
		end,
		--!!Split
		[5] = {CFrame.new,Flags[5] and 'dddddddddddd' or 'ffffffffffff'},
		--!!Split
		[6] = {Color3.fromRGB,'BBB'},
		--!!Split
		[7] = {BrickColor.new,'I2'},
		--!!Split
		[8] = function(Modifier)
			local len = Parse('I'..Modifier)
			local kpts = table.create(len)
			for i = 1,len do
				kpts[i] = ColorSequenceKeypoint.new(Parse('f'),Color3.fromRGB(Parse('BBB')))
			end
			return ColorSequence.new(kpts)
		end,
		--!!Split
		[9] = function(Modifier)
			local len = Parse('I'..Modifier)
			local kpts = table.create(len)
			for i = 1,len do
				kpts[i] = NumberSequenceKeypoint.new(Parse(Flags[5] and 'ddd' or 'fff'))
			end
			return NumberSequence.new(kpts)
		end,
		--!!Split
		[10] = {Vector3.new,Flags[5] and 'ddd' or 'fff'},
		--!!Split
		[11] = {Vector2.new,Flags[5] and 'dd' or 'ff'},
		--!!Split
		[12] = {UDim2.new,Flags[5] and 'di2di2' or 'fi2fi2'},
		--!!Split
		[13] = {Rect.new,Flags[5] and 'dddd' or 'ffff'},
		--!!Split
		[14] = function()
			local flags = Parse('B')
			local ids = {"Top","Bottom","Left","Right","Front","Back"}
			local t = {}
			for i = 0,5 do
				if bit32.extract(flags,i,1)==1 then
					table.insert(t,Enum.NormalId[ids[i+1]])
				end
			end
			return Axes.new(unpack(t))
		end,
		--!!Split
		[15] = function()
			local flags = Parse('B')
			local ids = {"Top","Bottom","Left","Right","Front","Back"}
			local t = {}
			for i = 0,5 do
				if bit32.extract(flags,i,1)==1 then
					table.insert(t,Enum.NormalId[ids[i+1]])
				end
			end
			return Faces.new(unpack(t))
		end,
		--!!Split
		[16] = {PhysicalProperties.new,Flags[5] and 'ddddd' or 'fffff'},
		--!!Split
		[17] = {NumberRange.new,Flags[5] and 'dd' or 'ff'},
		--!!Split
		[18] = {UDim.new,Flags[5] and 'di2' or 'fi2'},
		--!!Split
		[19] = function()
			return Ray.new(Vector3.new(Parse(Flags[5] and 'ddd' or 'fff')),Vector3.new(Parse(Flags[5] and 'ddd' or 'fff')))
		end
		--!!End
	}
	
	for i = 1,ValuesLength do
		local TypeAndModifier = Parse('B')
		local Type = bit32.band(TypeAndModifier,0b11111)
		local Modifier = (TypeAndModifier - Type) / 0b100000
		local Decoder = ValueDecoders[Type]
		if type(Decoder)=='function' then
			Values[i] = Decoder(Modifier,i)
		else
			Values[i] = Decoder[1](Parse(Decoder[2]))
		end
	end
	
	for i,t in pairs(CFrameIndexes) do
		Values[t[1]] = CFrame.fromMatrix(Values[t[2]],Values[t[3]],Values[t[4]])
	end
	
	local InstancesLength = Parse(InstanceFMT)
	local Instances = {}
	local NoParent = {}
	
	for i = 1,InstancesLength do
		local ClassName = Values[Parse(ValueFMT)]
		local obj
		local MeshPartMesh,MeshPartScale
		if ClassName == "UnionOperation" then
			obj = DecodeUnion(Values,Flags,Parse)
			obj.UsePartColor = true
		elseif ClassName:find("Script") then
			obj = Instance.new("Folder")
			Script(obj,ClassName=='ModuleScript')
		elseif ClassName == "MeshPart" then
			obj = Instance.new("Part")
			MeshPartMesh = Instance.new("SpecialMesh")
			MeshPartMesh.MeshType = Enum.MeshType.FileMesh
			MeshPartMesh.Parent = obj
		else
			obj = Instance.new(ClassName)
		end
		local Parent = Instances[Parse(InstanceFMT)]
		local PropertiesLength = Parse(PropertyLengthFMT)
		local AttributesLength = Parse(PropertyLengthFMT)
		Instances[i] = obj
		for i = 1,PropertiesLength do
			local Prop,Value = Values[Parse(ValueFMT)],Values[Parse(ValueFMT)]
			
			-- ok this looks awful
			if MeshPartMesh then
				if Prop == "MeshId" then
					MeshPartMesh.MeshId = Value
					continue
				elseif Prop == "TextureID" then
					MeshPartMesh.TextureId = Value
					continue
				elseif Prop == "Size" then
					if not MeshPartScale then
						MeshPartScale = Value
					else
						MeshPartMesh.Scale = Value / MeshPartScale
					end
				elseif Prop == "MeshSize" then
					if not MeshPartScale then
						MeshPartScale = Value
						MeshPartMesh.Scale = obj.Size / Value
					else
						MeshPartMesh.Scale = MeshPartScale / Value
					end
					continue
				end
			end
			
			obj[Prop] = Value
		end
		if MeshPartMesh then
			if MeshPartMesh.MeshId=='' then
				if MeshPartMesh.TextureId=='' then
					MeshPartMesh.TextureId = 'rbxasset://textures/meshPartFallback.png'
				end
				MeshPartMesh.Scale = obj.Size
			end
		end
		for i = 1,AttributesLength do
			obj:SetAttribute(Values[Parse(ValueFMT)],Values[Parse(ValueFMT)])
		end
		if not Parent then
			table.insert(NoParent,obj)
		else
			obj.Parent = Parent
		end
	end
	
	local ConnectionsLength = Parse(ConnectionFMT)
	for i = 1,ConnectionsLength do
		local a,b,c = Parse(InstanceFMT),Parse(ValueFMT),Parse(InstanceFMT)
		Instances[a][Values[b]] = Instances[c]
	end
	
	return NoParent
end


local Objects = Decode('AFTzAyEFTW9kZWwhCldvcmxkUGl2b3QEYQNiA2MDIQhNZXNoUGFydCEETmFtZSEgTWVzaGVzL2xvdmUgY2l0eV9NYXJpb19fQm9keU1UXzQhCEFuY2hvcmVkIiEGQ0ZyYW1lBBAAYgNkAyEITWF0ZXJpYWwDAAAAAACAlEAhC09yaWVudGF0aW9uCgAAkEAAAAAAAAAAACEIUG9zaXRpb24'
..'KwC5ywYhFED6vlLhCIQhSb3RhdGlvbiEEU2l6ZQpfTx5A+ug6PtX9oj8hBk1lc2hJZCEXcmJ4YXNzZXRpZDovLzI5NDUzNDA0MzchCE1lc2hTaXplCo9jRz8AaWs9AEnNPiEJVGV4dHVyZUlEIRdyYnhhc3NldGlkOi8vMjk0NTM2Mjk4NSEhTWVzaGVzL2xvdmUgY2l0eSAyX0hhaXJfX0'
..'hhaXJNVF8wBBwAYgNjAwqoIXPBkUCFQArUuEIKxT/QP1B8yj/0x9g/IRdyYnhhc3NldGlkOi8vMjk0NTM0ODg4MwoCbAw/vv8jPwCxLD8hF3JieGFzc2V0aWQ6Ly8yOTQ1Mzg0MTAxIS1NZXNoZXMvbG92ZSBjaXR5IDJfRXllYmFsbF9fRXllUHVwaWxSaWdodE1UXzAEIwBiA2MDCnCWd'
..'8F1eYVArO+5QgreKMY+tjkMP3yKHz4hF3JieGFzc2V0aWQ6Ly8yOTQ1MzQ5MDc3Cl6eBT6AGz0+AChXPSEXcmJ4YXNzZXRpZDovLzI5NjM1MjE5MTMhIU1lc2hlcy9sb3ZlIGNpdHkgMl9mYWNlX19GYWNlTVRfMAQqAGIDYwMK6OxywToneUBDm7lCClNyAkDvcMw/PufdPyEXcmJ4YXNz'
..'ZXRpZDovLzI5NDUzNDk1NjkKcusvP2ADBz8AoRU/IRdyYnhhc3NldGlkOi8vMjk0NTM5MzQyNiEiTWVzaGVzL2xvdmUgY2l0eSAyX01hcmlvX19Cb2R5TVRfMAQxAGIDZAMKgDZ1wXFkIkB6nLlCCqZFqD8sNJ0+4SYKPyEXcmJ4YXNzZXRpZDovLzI5NDUzNDk5ODYKmO/TPuD+xT0AAC4'
..'+IS9NZXNoZXMvbG92ZSBjaXR5IDJfbWFyaW9fdG9vdGhfYm90dG9tX19GYWNlTVRfMAQ3AGIDYwMK0E9zwUorXEDr1LlCCh7AAT9wo0g+8g6uPiEXcmJ4YXNzZXRpZDovLzI5NDUzNDk4MTgKHvsuPkBKhz0AvOo9IStNZXNoZXMvbG92ZSBjaXR5IDJfbWFyaW9fbXVzdGFjaGVfX0hhaX'
..'JNVF8wBD0AYgNjAwrQT3PBZk1yQFFdukIKzlmiP4ojCT94OK4+IRdyYnhhc3NldGlkOi8vMjk0NTM1MDU3MwoR8to+4PE4PgD06j0hF3JieGFzc2V0aWQ6Ly8yOTQ1MzkwMTE3ISxNZXNoZXMvbG92ZSBjaXR5IDJfRXllYmFsbF9fRXllUHVwaWxMZWZ0TVRfMAREAGIDYwMKQFJuwXV5h'
..'UCs77lCIRdyYnhhc3NldGlkOi8vMjk0NTM0ODk4NSEiTWVzaGVzL2xvdmUgY2l0eSAyX01hcmlvX19Cb2R5TVRfMwRIAGIDZAMKsE5zwQnxJUA1mbhCCgkXRECMJLE/5xGZPyEXcmJ4YXNzZXRpZDovLzI5NDUzNTAyMzAK3Ph2P8Ab3z4AysA+ISdNZXNoZXMvbG92ZSBjaXR5X21hcmlv'
..'X3Rvbmd1ZV9fRmFjZU1UXzAETgBiA2MDCtBPc8EyK1tARZK5Qgpfsd0+YBolPoeYzT4hF3JieGFzc2V0aWQ6Ly8yOTQ1MzM5ODM5Cq58FT5AqF49AKIKPiEgTWVzaGVzL2xvdmUgY2l0eV9NYXJpb19fQm9keU1UXzEEVABiA2QDCmBTcsHm3/Y+rbS4QgrXeCZAoHI0P5+buz8hF3JieGF'
..'zc2V0aWQ6Ly8yOTQ1MzQwMjE2CjarUT9gRWM+AErsPiEgTWVzaGVzL2xvdmUgY2l0eV9NYXJpb19fQm9keU1UXzUEWgBiA2MDCghdc8H6iV9Agmi4QgqEG/E+gge4PkNoDz8hF3JieGFzc2V0aWQ6Ly8yOTQ1MzM5NzI2CgiUIj5gLvg9AGZBPiEfTWVzaGVzL2xvdmUgY2l0eSAyX0NhcF'
..'9fQ2FwTVRfMARgAGIDYwMK4OFzwY2plEDkNrlCCsYV9T+Q8r0/oqwYQCEXcmJ4YXNzZXRpZDovLzI5NDUzNDg2NzgKNlAkP6D5AT+AAEw/IRdyYnhhc3NldGlkOi8vMjk0NTM4MDIzNSEpTWVzaGVzL2xvdmUgY2l0eV9tYXJpb190b290aF91cF9fRmFjZU1UXzAEZwBiA2MDCmBJc8EWF'
..'GNAwPy5QgrNSRc/jYsyPu60nj4hF3JieGFzc2V0aWQ6Ly8yOTQ1MzM5OTkyCtgGTD4AyXA9AAjWPSElTWVzaGVzL2xvdmUgY2l0eV9NYXJpb0hhbmRMX19IYW5kTVRfMARtAGIDZAMKEAJewdKSuj+SUrlCCsZ+Yz8GnLg/a6iaPyEXcmJ4YXNzZXRpZDovLzI5NDUzNDA2OTYKZEOPPjiD'
..'6D4AysI+IRdyYnhhc3NldGlkOi8vMjk0NTM2ODM3OSEpTWVzaGVzL2xvdmUgY2l0eSAyX21hcmlvX2Jyb3dfbF9fSGFpck1UXzAEdABiA2MDCkgnbsGBS49ADQS6QgpvDrc+pNWDPmAHMz4hF3JieGFzc2V0aWQ6Ly8yOTQ1MzUwMzk3Cnne9j2gyrE9AHBxPSEiTWVzaGVzL2xvdmUgY2l'
..'0eSAyX01hcmlvX19Cb2R5TVRfMgR6AGIDZAMK0EZywQtv7D8JpbhCCpmtE0CWlzZACOa3PyEXcmJ4YXNzZXRpZDovLzI5NDUzNTAxNDIKS1g3P8j4ZT8Anuc+ISVNZXNoZXMvbG92ZSBjaXR5X01hcmlvSGFuZFJfX0hhbmRNVF8wBIAAYgNkAwoQ64TBwi+/P61luEIKncVkP4yfuD8ZPK'
..'I/IRdyYnhhc3NldGlkOi8vMjk0NTM0MDc4Nwo3EZA+qIfoPgBVzD4hKU1lc2hlcy9sb3ZlIGNpdHkgMl9tYXJpb19icm93X3JfX0hhaXJNVF8wBIYAYgNjAwpYeHjBgUuPQA0EukIKdw63PqTVgz5gBzM+IRdyYnhhc3NldGlkOi8vMjk0NTM1MDQ4OQqF3vY9oMqxPQBwcT0hA1JpZwRlA'
..'2YDZwMhClJpZ2h0Rm9vdDIEaANpA2oDIQRQYXJ0IQZNaWRkbGUhFkFzc2VtYmx5TGluZWFyVmVsb2NpdHkKAAAAACoEKzgAAAAAIQtCYWNrU3VyZmFjZQMAAAAAAAAkQCENQm90dG9tU3VyZmFjZSEKQnJpY2tDb2xvcgcDBASgAGsDbAMhCkNhbkNvbGxpZGUCIQVDb2xvcgaf8+khDEZy'
..'b250U3VyZmFjZSELTGVmdFN1cmZhY2UDAAAAAAAAcUAKAAAAAAAAtEIAAAAACkRDMcFg5JE+oai/QiEMUmlnaHRTdXJmYWNlCgAAgD+mQtQ+AACAPyEKVG9wU3VyZmFjZSEMVHJhbnNwYXJlbmN5AwAAAAAAAPA/IQRXZWxkIQJDMAQMA20DbgMhAkMxIQVQYXJ0MCEFUGFydDEEbwNwA3E'
..'DBHIDcwN0AyEHTWlkZGxlMgMAAAAAAAAAAASyAHUDdgMKCtcnwQAAtMIAAAAACnn+MsHm+ZY+Wpy/QgoAALTCHwWfwgAAtMIhC1NwZWNpYWxNZXNoIRZyYnhhc3NldGlkOi8vMzg3OTM5OTEyIQhNZXNoVHlwZQMAAAAAAAAUQCEKUmlnaHQgRm9vdAS7AHcDeAMKAACowAAAtMIAAAAACu'
..'qfNsF+dxs/C6O/QgoAALTCAICpwgAAtMIK16OAP+F6ND/fT80/IRZyYnhhc3NldGlkOi8vNjY3Nzk3MjAzCvbHu0DwoINA5cYVQSEWcmJ4YXNzZXRpZDovLzY2NzkwMDU1OSEITGVmdEZvb3QH6gMExQBrA2wDBs3NzQpEQzHBYOSRPqGowUIKAACAP6CZmT4AAIA/ISlodHRwOi8vd3d3L'
..'nJvYmxveC5jb20vYXNzZXQvP2lkPTUwODI0ODAwOCEKQXR0YWNobWVudCEWTGVmdEFua2xlUmlnQXR0YWNobWVudATLAGIDdAMKAACAtIDPTD3071g1IQdNb3RvcjZEIQlMZWZ0QW5rbGUE8ABiA3QDIQhMZWZ0SGFuZATRAGsDbAMKREMxwYo8EkChqMNCCvz/fz+ZmZk+/v9/PyEpaHR0'
..'cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD01MDgyNDc5OTUhFkxlZnRXcmlzdFJpZ0F0dGFjaG1lbnQE1gBiA3QDCgAQ+zmZmRk+AACAMyESTGVmdEdyaXBBdHRhY2htZW50BNoAYgN5AwoAALTCAAAAgAAAAAAKAAAAtIGZGb5SGB20IQlMZWZ0V3Jpc3QE5QBiA3QDIQxMZWZ0TG9'
..'3ZXJBcm0E3wBrA2wDCkRDMcFXCT9AoajDQgr8/38/nJmZPwAAgD8hKWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA4MjQ3OTk2IRZMZWZ0RWxib3dSaWdBdHRhY2htZW50BOQAYgN0AwoA4Po5AQCAPu2AtB8KAOD6OczMDL/tgLQfIQlMZWZ0RWxib3cE+wBiA3QDIQxMZW'
..'Z0TG93ZXJMZWcE6gBrA2wDCkRDMcGA34o/oajBQgr//38/AwDAPwEAgD8hKWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA4MjQ4MDE1IRVMZWZ0S25lZVJpZ0F0dGFjaG1lbnQE7wBiA3QDCgAAAIDo/38+AABAtAoAAEC02P8/v/TvKDUhCExlZnRLbmVlBAoBYgN0AyEMT'
..'GVmdFVwcGVyQXJtBPUAawNsAwpEQzHBJdZbQKGow0IK/P9/PzYzsz///38/ISlodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwODI0Nzk5OSEZTGVmdFNob3VsZGVyUmlnQXR0YWNobWVudAT6AGIDdAMKUA6APmBm5j4AAMAzCgAw+znYzEy+AADAMyEWTGVmdFNob3VsZGVy'
..'QXR0YWNobWVudAT+AGIDdAMKAACANDgzMz+QwuiyIQxMZWZ0U2hvdWxkZXIEngFiA3QDBHoDYgN0AyEMTGVmdFVwcGVyTGVnBAQBawNsAwpEQzHB40XRP6GowUIKAwCAP/7/vz/+/38/ISlodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwODI0ODAxNiEUTGVmdEhpcFJpZ0F'
..'0dGFjaG1lbnQECQFiA3QDCgAAgDMAAAA/AAAwtAoAAIAzmJmZvgAAMLQhB0xlZnRIaXAEGAFiA3QDIQpMb3dlclRvcnNvBA8BawNsAwpEQzHBvm8VQKGowEIK/v//P8zMzD4BAIA/ISlodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwODI0ODAzMSERUm9vdFJpZ0F0dGFjaG'
..'1lbnQEFAFiA3QDCgAAALScmRk+AAAAgCESV2Fpc3RSaWdBdHRhY2htZW50BBcBYgN0AwoAAAC0zswMP+2AtB8KAgAAv8rMTL4AAACAIRVSaWdodEhpcFJpZ0F0dGFjaG1lbnQEGwFiA3QDCvz//z7KzEy+AAAAgCEVV2Fpc3RDZW50ZXJBdHRhY2htZW50BB4BYgN0Awpcj+K0AADgs/gXF'
..'jIhFFdhaXN0RnJvbnRBdHRhY2htZW50BCEBYgN0AwpS+A20AABAMwEAAL8hE1dhaXN0QmFja0F0dGFjaG1lbnQEJAFiA3QDCsI1HbQAAAAzAQAAPyEEUm9vdCEOUmlnaHRMb3dlckFybTIEewNrA2wDBCkBawNsAwpEQzHBVwk/QKGovUIKAACAP3L5Mz8AAIA/BAwDfAN9AwR+A38DgAME'
..'gQNzA3QDBDABggODAwoAAAAAAAC0wgAAAAAKGOgwwVcJP0C4nr1CIRZyYnhhc3NldGlkOi8vMzg3OTM4OTcxIQ9SaWdodCBMb3dlciBBcm0ENAGEA4UDClyvLcEHlD5Ae0e+QgrTTUI/5dBCPz0KFz8hFnJieGFzc2V0aWQ6Ly82Njc4ODM4OTAKbKyNQHwRjkDqbVxAIQlSaWdodEZvb3Q'
..'K//9/P6CZmT4AAIA/ISlodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwODI0ODAyMyEXUmlnaHRBbmtsZVJpZ0F0dGFjaG1lbnQEPQFiA3QDCgAAAICAzEw9yXjOOCEKUmlnaHRBbmtsZQRcAWIDdAMhCVJpZ2h0SGFuZARCAWsDbAMKREMxwYo8EkChqL1CCv7/fz+ZmZk+/v'
..'9/PyEpaHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD01MDgyNDgwMDEhF1JpZ2h0V3Jpc3RSaWdBdHRhY2htZW50BEcBYgN0AwoAAMA0mZkZPgAAgDMhE1JpZ2h0R3JpcEF0dGFjaG1lbnQESgFiA3kDCgAAAACBmRm+UhgdtCEKUmlnaHRXcmlzdARSAWIDdAMhDVJpZ2h0TG93Z'
..'XJBcm0hKWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA4MjQ4MDAzIRdSaWdodEVsYm93UmlnQXR0YWNobWVudARRAWIDdAMKAAAANAEAgD7tgLQfCgAAADTMzAy//C39oiEKUmlnaHRFbGJvdwRnAWIDdAMhDVJpZ2h0TG93ZXJMZWcEVwFrA2wDCkRDMcGA34o/oai/QiEp'
..'aHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD01MDgyNDgwMjYhFlJpZ2h0S25lZVJpZ0F0dGFjaG1lbnQEWwFiA3QDCgAAAIDo/38+sY82OAoAAACACABAv8kYzjghCVJpZ2h0S25lZQR1AWIDdAMhDVJpZ2h0VXBwZXJBcm0EYQFrA2wDCkRDMcEl1ltAoai9Qgr6/38/NjOzP//'
..'/fz8hKWh0dHA6Ly93d3cucm9ibG94LmNvbS9hc3NldC8/aWQ9NTA4MjQ4MDA0IRpSaWdodFNob3VsZGVyUmlnQXR0YWNobWVudARmAWIDdAMKqAKAvmBm5j4AAMAzCgAAILXYzEy+AADAMyEXUmlnaHRTaG91bGRlckF0dGFjaG1lbnQEagFiA3QDCgAAgLU4MzM/kMLosiENUmlnaHRTaG'
..'91bGRlcgSfAWIDdAMEhgNiA3QDIQ1SaWdodFVwcGVyTGVnBHABawNsAwpEQzHB40XRP6Gov0IKBACAP/7/vz/+/38/ISlodHRwOi8vd3d3LnJvYmxveC5jb20vYXNzZXQvP2lkPTUwODI0ODAyOAR0AWIDdAMKAAAAgAAAAD8AAOCzCgAAAICYmZm+sd82OCEIUmlnaHRIaXAhDlJpZ2h0T'
..'G93ZXJMZWcyBIcDiAN2AwoAAIA/t0JUPwAAgD8EiQNwA3EDBIoDcwN0AwR9AXUDdgMKmS4xwR7Qij9anL9CIRZyYnhhc3NldGlkOi8vMzg3OTM5NDg5IQ9SaWdodCBMb3dlciBMZWcEgQF3A3gDCiznMcFqIJg/C6O/Qgo+UmU/1wR1P1HnZz8hFnJieGFzc2V0aWQ6Ly82NjM0MDMyOTcK'
..'JU2nQO7AskByL6lAIQtMb3dlclRvcnNvMgSLA2YDZwMKAACAPwAAgD8AAIA/BAwDjAONAwSOA48DkAMEkQNzA3QDBIwBkgOTAwpc9y/BlG8VQF+fwEIhFnJieGFzc2V0aWQ6Ly8zODc5NDE3MTUhBVdhaXN0BJABlAOVAwq0cTHBz6IHQEytwEIKSC78P4Fahj/TY8c/IRZyYnhhc3NldGl'
..'kOi8vNjYzMzg3NzM5CoD6N0EKCcRACncRQSEKVXBwZXJUb3JzbwSWAWsDbAMKREMxwb5vVUChqMBCCgAAAEDOzMw/AwCAPyEpaHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD01MDgyNDgwMDcEmgFiA3QDCgAAgLNnZua+AAAANCERTmVja1JpZ0F0dGFjaG1lbnQEnQFiA3QDCg'
..'AAgLPMzEw/AAAANApw/J+/zMwMPwAAADQKXP+fP8zMDD8AAAA0IRNCb2R5RnJvbnRBdHRhY2htZW50BKIBYgN0AwoAAICz0MxMvvz//74hEkJvZHlCYWNrQXR0YWNobWVudASlAWIDdAMKAACAs9DMTL4AAAA/IRRMZWZ0Q29sbGFyQXR0YWNobWVudASoAWIDdAMK/v9/v9DMTD8YNZyzI'
..'RVSaWdodENvbGxhckF0dGFjaG1lbnQEqwFiA3QDCv//fz/MzEw/CCBGMwSWA2IDdAMhEEh1bWFub2lkUm9vdFBhcnQErwFrA2wDCkRDMcFYCR9AoajAQgoAAABAAAAAQAAAgD8hC1VwcGVyVG9yc28yBJcDZgNnAwS0AZIDkwMKXPcvwZRvNUBfn8BCIRZyYnhhc3NldGlkOi8vMzg3OTQx'
..'NDY4BLcBawNsAwpEQzHBvm81QKGowEIEmANzA3QDIQVDaGVzdAS7AZQDlQMKtHExwcKiOUBMrcBCCuOl6z/VeNk/sp3PPyEWcmJ4YXNzZXRpZDovLzY2Nzg4NTUxMwr85StBKqkeQUB0F0EhDlJpZ2h0VXBwZXJMZWcyBJkDmgObAwoAAIA/yFtGPwAAgD8EDAOcA50DBJ4DnwOgAwShA3M'
..'DdAMExwGiA6MDCgrXI7wAALTCAAAAAAq49y/BbEXRP1qcv0IhFnJieGFzc2V0aWQ6Ly8zODc5Mzk2NDUhD1JpZ2h0IFVwcGVyIExlZwTLAaQDpQMK4nExwcFLzz8Lo79CCpNPfD+Mc6c/yZiDPyEWcmJ4YXNzZXRpZDovLzY2MzQwMTkwMwrKErhAEVT0QFQDwEAhDlJpZ2h0VXBwZXJBcm'
..'0yBKYDpwOoAwTSAWsDbAMKREMxwSXWW0CCI71CCgAAgD+o4Ss/AACAPwQMA6kDqgMEqwOsA60DBK4DcwN0AwTZAa8DqAMK7FGgwAAAtMIAAAAACuNvMMG0t1tAmRm9QgoAALTC4fqpwgAAtMIKAACAP2UXLD8AAIA/IRZyYnhhc3NldGlkOi8vMzg3OTM4NDY4IQ9SaWdodCBVcHBlciBBc'
..'m0E4AGwA7EDCtejIMAAALTCAAAAAAr7PC/BrXVKQM5xvkIKAAC0wuH6rsIAALTCCq3SUj+7rk4/NnZFPyEWcmJ4YXNzZXRpZDovLzY2MzM5NTgzOQpQzplACsmWQO0OkEAhBEhlYWQE5wFrA2wDCiZCMcGshJdAoajAQgoAAABAAACAPwAAgD8DAAAAgBSu7z8hBVNjYWxlCgAAoD8AAKA/'
..'AACgPyEURmFjZUNlbnRlckF0dGFjaG1lbnQE7wGyA7MDChzi1ShGdkMqfyDytAozt2uzAAAAAADAjrkhE0ZhY2VGcm9udEF0dGFjaG1lbnQE8gGyA7MDCjK3a7MAAAAAcqsZvyEOSGFpckF0dGFjaG1lbnQE9QGyA7MDCmZuV7OcmRk/AMCOuSENSGF0QXR0YWNobWVudCEOTmVja0F0dGF'
..'jaG1lbnQE+QGyA7MDCtdDWbOYmRm/dMaOuQT7AWIDdAMKAACAs5qZGb8AwI65IQVEZWNhbCEEZmFjZSEHVGV4dHVyZSEoaHR0cDovL3d3dy5yb2Jsb3guY29tL2Fzc2V0Lz9pZD0xMDc0NzkxMSEETmVjayEFU291bmQhCUdldHRpbmdVcCESUm9sbE9mZk1heERpc3RhbmNlAwAAAAAAwG'
..'JAIRJSb2xsT2ZmTWluRGlzdGFuY2UhB1NvdW5kSWQhI3JieGFzc2V0Oi8vc291bmRzL2FjdGlvbl9nZXRfdXAubXAzIQZWb2x1bWUDAAAAwMzM5D8hBERpZWQhG3JieGFzc2V0Oi8vc291bmRzL3V1aGhoLm1wMyELRnJlZUZhbGxpbmchBkxvb3BlZCEkcmJ4YXNzZXQ6Ly9zb3VuZHMvY'
..'WN0aW9uX2ZhbGxpbmcubXAzIQdKdW1waW5nISFyYnhhc3NldDovL3NvdW5kcy9hY3Rpb25fanVtcC5tcDMhB0xhbmRpbmchJnJieGFzc2V0Oi8vc291bmRzL2FjdGlvbl9qdW1wX2xhbmQubXAzIQZTcGxhc2ghInJieGFzc2V0Oi8vc291bmRzL2ltcGFjdF93YXRlci5tcDMhB1J1bm5p'
..'bmchDVBsYXliYWNrU3BlZWQDAAAAoJmZ/T8hLnJieGFzc2V0Oi8vc291bmRzL2FjdGlvbl9mb290c3RlcHNfcGxhc3RpYy5tcDMhCFN3aW1taW5nAwAAAKCZmfk/ISFyYnhhc3NldDovL3NvdW5kcy9hY3Rpb25fc3dpbS5tcDMhCENsaW1iaW5nIQhIdW1hbm9pZCEJSGlwSGVpZ2h0AwA'
..'AAKCZmfU/IQdSaWdUeXBlIQhBbmltYXRvciEKUmlnaHRIYW5kMgS0A7UDtgMKAACAP2L5sz4AAIA/BLcDfwOAAwS4A3MDdAMEKAKCA4MDChjoMMFcPBJAuJ69QiEWcmJ4YXNzZXRpZDovLzM4NzkzOTIzMyEKUmlnaHQgSGFuZAQsAoQDhQMKRA4vwR6gEkBNQL1CCkR2mj/2xZo/6g6TPy'
..'EWcmJ4YXNzZXRpZDovLzY2MzM5OTgzOQogYOFAbtThQKSS1kAhBUhlYWQyBLkDZgNnAwS6A7sDdAMEvANzA3QDBDUCvQOVAwpSVTHBl4SXQF+fwEIhHHJieGFzc2V0Oi8vdGV4dHVyZXMvZmFjZS5wbmcEOAKUA5UDCgZ/M8EuuZtATK3AQgr4UytAIbAyQJhuSkAhFnJieGFzc2V0aWQ6L'
..'y82Njc4OTkyNDMK+vx5QRJXgkHEtJNBIQZTY3JpcHQhCUxlZnRGb290MgS+A78DwAMEDAPBA8IDBMMDxAPFAwTGA3MDdAMEQwLHA8gDCnn+MsHm+ZY+WJzBQiEWcmJ4YXNzZXRpZDovLzM4Nzk0MTE5NiEJTGVmdCBGb290BEcCyQPAAwrqnzbBfXcbP4i0wUIKheuBP0a2Mz8/Nc4/IRZy'
..'Ynhhc3NldGlkOi8vNjY3Nzk2NjMzCv6bvUDGLYNA23IWQSEJTGVmdEhhbmQyBMoDywPMAwQMA80DzgMEtwPPA9ADBNEDcwN0AwRRAtID0wMKGOgwwVw8EkC4nsNCIRZyYnhhc3NldGlkOi8vMzg3OTQwNTQ4IQlMZWZ0IEhhbmQEVQLUA9UDCkQOL8EroBJApRnEQgrYt50/Tx6cP6gRlD8'
..'hFnJieGFzc2V0aWQ6Ly82NjMzOTg3NzAKZyDmQN7K40ArDNhAIQ1MZWZ0TG93ZXJBcm0yBNYDawNsAwR+A88D0AME1wNzA3QDBF4C0gPTAwoY6DDBVwk/QLiew0IhFnJieGFzc2V0aWQ6Ly8zODc5NDAzNTYhDkxlZnQgTG93ZXIgQXJtBGIC1APVAwpcry3BB5Q+QHkSw0IK1vY4PxNHQj'
..'9OOxw/IRZyYnhhc3NldGlkOi8vNjYzMzk3MTk0Cs/whkA+vI1ALPVjQCENTGVmdExvd2VyTGVnMgTYA9kDyAMEaQLHA8gDCpkuMcEe0Io/WpzBQiEWcmJ4YXNzZXRpZDovLzM4Nzk0MDgwMgSJA8QDxQME2gNzA3QDIQ5MZWZ0IExvd2VyIExlZwRvAskDwAMKLOcxwWogmD+KtMFCCihFZ'
..'T+mWHI/8JtoPyEWcmJ4YXNzZXRpZDovLzY2MzQwMjU0NAqZQ6dAx82wQDizqUAhDUxlZnRVcHBlckFybTIE2wPcA90DBHYCawNsAwpEQzHBJdZbQMAtxEIEDAPeA98DBOAD4QPiAwTjA3MDdAMEewLkA+UDCgtwMMFAqltA1yPEQiEWcmJ4YXNzZXRpZDovLzM4Nzk0MDExMyEOTGVmdCBV'
..'cHBlciBBcm0EfwLmA+cDCv48L8EHb0pAJOjCQgo9Clc/okVWP3E9Sj8hFnJieGFzc2V0aWQ6Ly82Njc4ODQxMTUKnuqcQK5ZnEAWm5NAIQ1MZWZ0VXBwZXJMZWcyBOgDmgObAwTpA3MDdAMEhwKiA6MDCrj3L8FsRdE/WpzBQiEWcmJ4YXNzZXRpZDovLzM4Nzk0MDk3NiEOTGVmdCBVcHB'
..'lciBMZWcEiwKkA6UDCuJxMcHBS88/irTBQgqNvn4/9FSnP/h4gj8hFnJieGFzc2V0aWQ6Ly82NjM0MDEyNzcKSNm5QG0n9EBgX75AIRJNYXJpbydzIEl0ZW0gQmxvY2sE6gNiA3QDB+kDBJUC6wNiAwb4+PgKAAAAAAAAAAAAALTCCnNmGsEMM3NA4UzPQgrNzMw+zczMPs3MzD4hBVNoYX'
..'BlAwAAAAAAAABABJoC6wNiAwozAEzBwMxMPuVMz0IEnQLsA7sDCgAAtMIAADTDAAAAAAozAFDBBDNjQK8ZyUIKAAC0wgAAAAAAADTDBKAC6wNiAwozAEzBwMxMPqkZyUIEogLsA7sDCjMAUMEEM2NA60zPQgSkAusDYgMKc2YawcDMTD7hTM9CBKYC7AO7AwrjZhbBYGbmPuVMz0IEqQK7A'
..'2IDCgAAtMIAALTCAAAAAApBAEzBYGbmPvPMz0IKAAC0wgAAAAAAALTCBKwC6wNiAwpzZhrBDDNzQKkZyUIErgLrA2IDCjMATMEMM3NAqRnJQgSwAuwDuwMKMwBQwWBm5j7nTM9CBLICuwNiAwpBAEzBBDNjQLGZyEIEtALsA7sDCuNmFsEEM2NArxnJQgcYAAS4AmIDdAMG9c0wCkIzM8HI'
..'//8/RjPMQgqamXlAmpl5QJqZeUAEuwK7A2IDCnNmGsEEM2NAsZnIQgS9AusDYgMKMwBMwQwzc0DlTM9CBL8C6wNiAwpzZhrBwMxMPqkZyUIEwQLsA7sDCuNmFsFgZuY+qRnJQgTDArsDYgMKMwBMwQQzY0DtzM9CBMUCuwNiAwpjZhrBYGbmPrGZyEIEyAJzA2IDCgAAtEIAALRCAAAAAAp'
..'zZhrBBDNjQO3Mz0IKAAC0QgAAAAAAALTCBMsCuwNiAwpjZhrBYGbmPvPMz0IEzQLsA7sDCuNmFsEEM2NA5UzPQgTPArsDYgMKQQBMwWBm5j6xmchCBNEC7AO7AwozAFDBYGbmPq8ZyUIhDlVuaW9uT3BlcmF0aW9uIQk/IE1BUkshISEE1QK7A3QDCjIzM8HI//8/mZnIQgrNzMw+MzMzQG'
..'ZmJkAKecbMPtuUGT93xkw/CqOZMcGwbmY/mZnIQiEJV2VkZ2VQYXJ0Cg/GzD4Pxsw+kPf/PgpA/0PBV8pMQJmZyEIKD8bMPhDGTD8Nxkw/CmOZQcE1ZSZAmZnIQgoPxsw+D8bMPm+S2T8Kv2YywVbKTECZmchCCiP/Q8EBAABAmZnIQgoAAAAAAAC0QgAANEMKD8bMPg/GzD6O9/8+Cu4yN'
..'8EbZgZAmJnIQgoaMy/BV2YGQJmZyEIKD8bMPouUGT8Nxkw/CmyZMcGxzsw/mpnIQgoryIw/jJQZPw3GTD8KcpkxwcLOzD/QTMhCChDGzD4Qxsw+EMbMPgqM/zfBMZrZP5yZyEIKi5SZP4uUGT8Nxkw/CkXMPMFfAsA/mpnIQgoRxsw+EcbMPhHGzD4KWcw8wVz//z+WmchCCo6UGT+W938/'
..'kvf/PgoCMzfBcWfmP8XMyEIKEMbMPk8tMz8Oxkw/CpTNJMF6mClAmZnIQgrpmSHBU8pMQJmZyEIE9QJzA3QDCjIzM8HI//8/zczPQgrBzDTBsG5mP83Mz0IKJGciwVfKTEDNzM9CCgHNJME1ZSZAzczPQgql/zPBVspMQM3Mz0IKQWciwQEAAEDNzM9CCgAAAAAAALTCAAA0Qwp2My/BG2Y'
..'GQM7Mz0IKSjM3wVdmBkDNzM9CCvjMNMGxzsw/zMzPQgryzDTBws7MP5YZ0EIK2GYuwTGa2T/KzM9CCh+aKcFfAsA/zMzPQgoLminBXP//P9DMz0IKYjMvwXFn5j+hmc9CCtCYQcF6mClAzczPQgp7zETBU8pMQM3Mz0IECAPsA3QDCgAAAAAAADRDAAAAAApzZhbByP//PzUzzEIKAAA0ww'
..'AAAAAAADTDCm9mFsGwbmY/Z2bMQgpvZhbBV8pMQLMZykIKAAAAAAAAAAAAAAAACm9mFsE1ZSZAbmbKQgpvZhbBVspMQMNMzEIKdGYWwQEAAEC2GcpCCgAAAAAAAAAAAAA0QwpsZhbBG2YGQD2zy0IKcGYWwVdmBkA3s8xCCnhmFsGxzsw/bWbMQgooABTBws7MP2xmzEIKjGYWwTGa2T+pm'
..'ctCCnhmFsFfAsA/EgDLQgpYZhbBXP//PxAAy0IK0v8XwXFn5j87s8tCCm9mFsF6mClA6f/NQgpvZhbBU8pMQF5mzkIEHANiA3QDCgMAUMHI//8/NTPMQgoHAFDBsG5mPwMAzEIKBwBQwVfKTEC3TM5CCgcAUME1ZSZA/P/NQgoHAFDBVspMQKcZzEIKAgBQwQEAAEC0TM5CCgAAAAAAADRD'
..'AAA0QwoKAFDBG2YGQC2zzEIKBgBQwVdmBkAzs8tCCv7/T8Gxzsw//f/LQgpOZlLBws7MP/7/y0IK6v9PwTGa2T/BzMxCCv7/T8FfAsA/WGbNQgoeAFDBXP//P1pmzUIKpGZOwXFn5j8vs8xCCgcAUMF6mClAgWbKQgoHAFDBU8pMQAwAykIhCUJvb2xWYWx1ZSELUm9ibG94TW9kZWwhDVJ'
..'vYmxveFN0YW1wZXIhBFN0YXIhC1ByaW1hcnlQYXJ0BDQD7QN0AwoAAAAAAACvwgAAAAAKAEStwcEWBEHdqsRCCgAAAAAfBa/CAAAAAAoAAIBAAACAQM3MTD4hC0F0dGFjaG1lbnQxBAwD7gPvAwri/h/ANf8fwO87KDYhClBvaW50TGlnaHQhCkJyaWdodG5lc3MDAAAAAAAAGEAhBVJhbm'
..'dlIQ9QYXJ0aWNsZUVtaXR0ZXIhBFJpbmcoAgAAAADP+f8AAIA/zf+KIQhMaWZldGltZREAAIBAAACgQCENTGlnaHRFbWlzc2lvbiEMTG9ja2VkVG9QYXJ0IQRSYXRlIQhSb3RTcGVlZBEAACDBAADwQSkCAAAAAAAAAEEAAAAAAACAPwAAAEEAAAAAIQVTcGVlZBEAAAAAAAAAACEWcmJ4Y'
..'XNzZXRpZDovLzU1OTE1NzkyNCkEAAAAAAAAgD8AAAAAzcxMPQAAgD4AAAAAAABAPwAAgD4AAAAAAACAPwAAgD8AAAAACgAAQEAAAEBAAABAQCEWcmJ4YXNzZXRpZDovLzUxNjAzMjY1MiEJVGV4dHVyZUlkIRZyYnhhc3NldGlkOi8vNTE2MDMyMzQ4BPAD7AN0AwTxA2IDdAMhBEV5ZXMH'
..'6wMEWAPyA3QDBhEREQoAAAAAAAC5QgAAAAAK1qqrwehyA0FmpsRCCgAANMMfBa9CAAA0wwrNzEw+zcxMPs3MTD4hCk1hbnVhbFdlbGQE8wNiA3QDIQZPZmZzZXQKAAAAAAAAAACamRk/CmZm5j9mZuY/ZmbmPyEWcmJ4YXNzZXRpZDovLzUwMjQwNjQ2MQow8XPB5WcsQOQ2uUIKAACAPwA'
..'AAAAAAAAACgAAAAACAIA/AQCAsgoAAAAAXjZ/Pz+IoD0KB38zwThlSEA7sMBCCgAAgKAAAICkAACAPwr+/38oAACAPwAAgKQKUiQ2weBVAj99or9CCmYyPa4A5SssAACAPwocQ7s9du1+PwA40ysKgD+1rCdjAbAAAIC/CvIAULMAAIA/KGMBsAqAP7WsIkO7vXbtfj8KJ2MBsHbtfj8iQ7'
..'s9CgBwxDwA4CI8AJrdvQoJbreuG0O7PXbtfr8K826GtXbtfj8bQ7s9CgDAMjxJqZS+APS5vgoAAAAAAAAAAAAAgL8KAAAAAAAAgD8AAAAACuLxxLNw3oW1AACAPwpJejo+Jrh7PzvfhTUKZjI9rvXkKywAAIA/ChxDuz127X4/dzfTKwoAAAAAMjGNJAAAgL8KuB6FvgAAAAAAAAAACq4VM'
..'cEIlD5AP9S9QgqAP7WsAABQswAAgD8KJ2MBsAAAgD8AAFAzCgCQnjwAAAAAAFi2PAqlr5otAAA+lgEAgL8Kz9ncsAEAgD8AAD4WCgDanr4AoOo7APpkPgqkr5ot0NncsAAAgD8KAAByqwEAgD/Q2dwwCgAAwKFEk4CkAACAPwoAAHKrAACAP0STgKQKuB6FPgAAAAAAAAAACtMYMcHACJI/'
..'faK/Qgri8cSzb96FtQAAgD8KAHDEPADA77kAYKU7CgDAMjzgrMu9AABKvQq0cTHB+L0NQEutwEIKgD+1rPQAULMAAIA/CidjAbAAAIA/9QBQMwoAIJQ8AAAoNwD0pT0Kpa+aLXt9iR4AAIC/Cs/Z3LAAAIA/32aBngoAYBW88M5cPgDAObwKpa+aLdDZ3LAAAIA/CgAAQCgAAIA/ztncMAo'
..'AAAAARJOApAAAgD8KAABAKAAAgD9Ek4CkCgAAAAAAAAC/AAAAAAq0cTHBwKI5QEutwEIKAGAVvIBghr0AwDm8CoDRMMGgS88/faK/QgrAG1apAAAAJgAAgD8K9s/TOAAAgD8AACCmCoA/taz26dO4AACAPwonYwGwAACAP/bp0zgKAHDEPAAAELYAxqU9CqWvmi32z9M4AACAvwrP2dywAA'
..'CAP/bP0zgKAMAyPAAWfTwAcDq8CiHXmC3a2dywAACAPwr2z1M5AACAP7vZ3DAKgBtWqdja/yUAAIA/CvbP0zgAAIA/KAkmpgqcRTHBEChSQB2vvUIK6lShruem3LAAAIA/Cv8Asz0xBX8/VrDcMAqAP7WsQUkzvTHBfz8KJ2MBsDHBfz9BSTM9CgCQnjwAUC67ADxTPQqlr5otmRAzPVnBf'
..'78Kz9ncsFnBfz+ZEDM9CgAmJ7+wC4g+AJ4NPgrqVKGu5qbcsAAAgD8Kiy+1relvPisAAIA/CjRJMz0xwX8/LQF+KgoAAIA/rToHskpVWqcKrToHMgAAgD/t6O4lCkyQL8EgoBJAAVq9QgoAAOChAACApAAAgD8KAABwqwAAgD8AAICkCgCQnjwAADg3AFi2PAoAqFA+ACjHuwBADT4KBn8z'
..'wSy5m0BLrcBCCgAglLwAACg3AGCZOwoAAAAAAAAAAAAAgD8KAGAVvECQBr4AOA++CgAAAABEk4AkAACAvwq+KzbBgC8CP1uqwUIKITzEswiohbUAAIA/ChxDuz127X4/yjeGNQo94dIuIkO7vXbtfj8K6UeGtXbtfj8iQ7s9CgCQxDwA4CI8AJrdvQqlr5otG0O7PXbtfr8Kz9ncsHbtfj8'
..'bQ7s9CgBwvrxJqZS+APS5vgpHg8SzEt+FtQAAgD8KSXo6Pia4ez+Z3oU1CiE8xLMJqIW1AACAPwo2iC/BKKASQOf5w0IKAAAQIgAAAKUAAIA/CgAAdKsBAIA/AAAApQqAP7WsAABQswEAgD8KJ2MBsAEAgD8AAFAzCqWvmi0AAECWAACAvwrP2dywAACAPwAAQBYKAAhivgBCx7sAQA0+Cq'
..'evmi3S2dywAACAPwoAAHSrAQCAP9DZ3DAKAAAgIqJJAKUAAIA/CgAAdKsBAIA/okkApQpkCDHBCJQ+QBGBw0IKACiWPgCg6jsA+mQ+CrgaMcEAt5E/faLBQgpHg8SzEd+FtQAAgD8KAJC+vOCsy70AAEq9CvUzMcGYpFFAbZ/DQgrCFaGuEafcsAAAgD8KAAGzPTMFfz8ksNwwCoA/taynE'
..'DO9W8F/PwonYwGwW8F/P6cQMz0KAJCePAD48LoAYFM9CqWvmi00STM9McF/vwrP2dywMcF/PzRJMz0KAM4iP9BBiD4Ang0+CsIVoa4Qp9ywAACAPwoAAbM9MwV/PyOw3DAKWva0rekDPisAAIA/CpoQMz1bwX8/U/F8KgqByDDBoEvPP9GnwUIKAJC+vAAWfTwAcDq8ClMzM8EMAABARTPM'
..'QgoAAAAAAACAvwAAAAAKAACAvwAAAAAAAAAACrapMj0AAAAAJMJ/PwqiwX8/kL07M1ypMj0K7F35OqLBfz93fTK9CgAAAAAAAAAAzczMvQoAAAAAANgjPQDAzL0KtqkyvQAAAAAkwn+/CgAAwLYAAIC1AADAtisBAQAAAAEAAgADAAQAAQALAAUABgAHAAgACQAKAAsADAANAA4ADwAQABE'
..'ADgASABMAFAAVABYAFwAYABkABAABAAkABQAaAAcACAAJABsACwAMAA8AHAASAB0AFAAeABYAHwAYACAABAABAAkABQAhAAcACAAJACIACwAMAA8AIwASACQAFAAlABYAJgAYACcABAABAAkABQAoAAcACAAJACkACwAMAA8AKgASACsAFAAsABYALQAYAC4ABAABAAsABQAvAAcACAAJAD'
..'AACwAMAA0ADgAPADEAEQAOABIAMgAUADMAFgA0ABgAGQAEAAEACQAFADUABwAIAAkANgALAAwADwA3ABIAOAAUADkAFgA6ABgALgAEAAEACQAFADsABwAIAAkAPAALAAwADwA9ABIAPgAUAD8AFgBAABgAQQAEAAEACQAFAEIABwAIAAkAQwALAAwADwBEABIAJAAUAEUAFgAmABgAJwAEA'
..'AEACwAFAEYABwAIAAkARwALAAwADQAOAA8ASAARAA4AEgBJABQASgAWAEsAGAAZAAQAAQAIAAUATAAHAAgACQBNAAsADAAPAE4AEgBPABQAUAAWAFEABAABAAsABQBSAAcACAAJAFMACwAMAA0ADgAPAFQAEQAOABIAVQAUAFYAFgBXABgAGQAEAAEACQAFAFgABwAIAAkAWQALAAwADwBa'
..'ABIAWwAUAFwAFgBdABgALgAEAAEACQAFAF4ABwAIAAkAXwALAAwADwBgABIAYQAUAGIAFgBjABgAZAAEAAEACQAFAGUABwAIAAkAZgALAAwADwBnABIAaAAUAGkAFgBqABgALgAEAAEACwAFAGsABwAIAAkAbAALAAwADQAOAA8AbQARAA4AEgBuABQAbwAWAHAAGABxAAQAAQAJAAUAcgA'
..'HAAgACQBzAAsADAAPAHQAEgB1ABQAdgAWAHcAGABBAAQAAQALAAUAeAAHAAgACQB5AAsADAANAA4ADwB6ABEADgASAHsAFAB8ABYAfQAYABkABAABAAsABQB+AAcACAAJAH8ACwAMAA0ADgAPAIAAEQAOABIAgQAUAIIAFgCDABgAcQAEAAEACQAFAIQABwAIAAkAhQALAAwADwCGABIAhw'
..'AUAIgAFgCJABgAQQABAAAAAgAFAIoAAgCLAAEAFQACAAUAjAACAI0AjgAWABIABQCPAJAAkQCSAJMAlACTAJUAlgAJAJcAmACZAJoAmwCcAJMAnQCTAAsAngANAJ8ADwCgAKEAkwARAJ8AEgCiAKMAkwCkAKUApgAXAAIApwCoAKkAqACmABcAAgCnAKgAqQCsAKYAFwACAKcAqACpAK0Aj'
..'gAWAAsABQCuAJAAkQCUAK8ACQCwAJgAmQANALEADwCyABEAswASAKIAowCvAKQApQC0ABsAAgAUALUAtgC3AAQAFgAMAAUAuACQAJEACQC5AJgAmQALAAwADQC6AA8AuwARALwAEgC9ABQAvgAWAL8AGADAAAQAFQANAAUAwQCQAJEAlQDCAAkAwwCYAJkAmgDEAA0AnwAPAMUAEQCfABIA'
..'xgCkAKUAFADHABYAxgDIAB4AAwAFAMkACQDKAA8AywDMAB4AAwAFAM0ApwDOAKkAygCmAB4AAAAEABUADQAFAM8AkACRAJUAwgAJANAAmACZAJoAxAANAJ8ADwDRABEAnwASANIApAClABQA0wAWANIAyAAiAAMABQDUAAkA1QAPANYAyAAiAAQABQDXAAkA2AANANkADwDaAMwAIgADAAU'
..'A2wCnANwAqQDVAKYAIgAAAAQAFQANAAUA3QCQAJEAlQDCAAkA3gCYAJkAmgDEAA0AnwAPAN8AEQCfABIA4ACkAKUAFADhABYA4ADIACcAAwAFAOIACQDjAA8A5ADIACcAAwAFANQACQDcAA8A5QDMACcAAwAFAOYApwDnAKkA4wCmACcAAAAEABUADQAFAOgAkACRAJUAwgAJAOkAmACZAJ'
..'oAxAANAJ8ADwDqABEAnwASAOsApAClABQA7AAWAOsAyAAsAAMABQDtAAkA7gAPAO8AyAAsAAMABQDJAAkAzgAPAPAAzAAsAAMABQDxAKcA8gCpAO4ApgAsAAAABAAVAA0ABQDzAJAAkQCVAMIACQD0AJgAmQCaAMQADQCfAA8A9QARAJ8AEgD2AKQApQAUAPcAFgD2AMgAMQADAAUA+AAJA'
..'PkADwD6AMgAMQADAAUA4gAJAOcADwD7AMgAMQADAAUA/AAJAP0ADwD+AMwAMQADAAUA/wCnAAABqQD5AKYAMQABAKcAAQEEABUADQAFAAIBkACRAJUAwgAJAAMBmACZAJoAxAANAJ8ADwAEAREAnwASAAUBpAClABQABgEWAAUByAA3AAMABQAHAQkACAEPAAkByAA3AAMABQDtAAkA8gAP'
..'AAoBzAA3AAMABQALAacADAGpAAgBpgA3AAAABAAVAAwABQANAZAAkQCVAMIACQAOAZoAxAANAJ8ADwAPAREAnwASABABpAClABQAEQEWABAByAA8AAMABQASAQkAEwEPABQByAA8AAMABQAVAQkAFgEPABcByAA8AAMABQAHAQkADAEPABgByAA8AAMABQAZAQkAGgEPABsByAA8AAMABQA'
..'cAQkAHQEPAB4ByAA8AAMABQAfAQkAIAEPACEByAA8AAMABQAiAQkAIwEPACQBzAA8AAIABQAlAakAEwGmADwAAAABABUAAgAFACYBAgAnAY4ARgASAAUAjwCQAJEAkgCTAJQAkwCVAJYACQAoAZgAmQCaAJsAnACTAJ0AkwALAJ4ADQCfAA8AKQGhAJMAEQCfABIAKgGjAJMApAClAKYARw'
..'ACAKcAKwGpACsBpgBHAAIApwArAakALAGmAEcAAgCnACsBqQAtAY4ARgALAAUArgCQAJEAlACvAAkALgGYAJkADQAvAQ8AMAERAC8BEgAqAaMArwCkAKUAtABLAAIAFAAxAbYAtwAEAEYADAAFADIBkACRAAkAMwGYAJkACwAMAA0ALwEPADQBEQAvARIANQEUADYBFgA3ARgAwAAEABUAD'
..'QAFADgBkACRAJUAwgAJAJcAmACZAJoAxAANAJ8ADwCgABEAnwASADkBpAClABQAOgEWADkByABOAAMABQA7AQkAPAEPAD0BzABOAAMABQA+AacAPwGpADwBpgBOAAAABAAVAA0ABQBAAZAAkQCVAMIACQBBAZgAmQCaAMQADQCfAA8AQgERAJ8AEgBDAaQApQAUAEQBFgBDAcgAUgADAAUA'
..'RQEJAEYBDwBHAcgAUgAEAAUASAEJAEkBDQDZAA8ASgHMAFIAAwAFAEsBpwBMAakARgGmAFIAAAAEABUADQAFAE0BkACRAJUAwgAJACgBmACZAJoAxAANAJ8ADwApAREAnwASAOAApAClABQATgEWAOAAyABXAAMABQBPAQkAUAEPAFEByABXAAMABQBFAQkATAEPAFIBzABXAAMABQBTAac'
..'AVAGpAFABpgBXAAAABAAVAA0ABQBVAZAAkQCVAMIACQBWAZgAmQCaAMQADQCfAA8AVwERAJ8AEgDrAKQApQAUAFgBFgDrAMgAXAADAAUAWQEJAFoBDwBbAcgAXAADAAUAOwEJAD8BDwBcAcwAXAADAAUAXQGnAF4BqQBaAaYAXAAAAAQAFQANAAUAXwGQAJEAlQDCAAkAYAGYAJkAmgDEAA'
..'0AnwAPAGEBEQCfABIAYgGkAKUAFABjARYAYgHIAGEAAwAFAGQBCQBlAQ8AZgHIAGEAAwAFAE8BCQBUAQ8AZwHIAGEAAwAFAGgBCQBpAQ8AagHMAGEAAwAFAGsBpwBsAakAZQGmAGEAAQCnAG0BBAAVAA0ABQBuAZAAkQCVAMIACQBvAZgAmQCaAMQADQCfAA8AcAERAJ8AEgBxAaQApQAUA'
..'HIBFgBxAcgAZwADAAUAGQEJAHMBDwB0AcgAZwADAAUAWQEJAF4BDwB1AcwAZwADAAUAdgGnABoBqQBzAaYAZwAAAAEAFQACAAUAdwECAHgBjgBsABIABQCPAJAAkQCSAJMAlACTAJUAlgAJAFYBmACZAJoAmwCcAJMAnQCTAAsAngANAJ8ADwBXAaEAkwARAJ8AEgB5AaMAkwCkAKUApgBt'
..'AAIApwCoAKkAqACmAG0AAgCnAKgAqQB6AaYAbQACAKcAqACpAHsBjgBsAAsABQCuAJAAkQCUAK8ACQB8AZgAmQANALEADwB9AREAswASAHkBowCvAKQApQC0AHEAAgAUAH4BtgC3AAQAbAAMAAUAfwGQAJEACQCAAZgAmQALAAwADQC6AA8AgQERALwAEgCCARQAgwEWAIQBGADAAAEAFQA'
..'CAAUAhQECAIYBjgB0ABIABQCPAJAAkQCSAJMAlACTAJUAlgAJAA4BmACZAJoAmwCcAJMAnQCTAAsAngANAJ8ADwAPAaEAkwARAJ8AEgCHAaMAkwCkAKUApgB1AAIApwCIAakAiAGmAHUAAgCnAIgBqQCJAaYAdQACAKcAiAGpAIoBjgB0AAsABQCuAJAAkQCUAK8ACQCLAZgAmQANAC8BDw'
..'CMAREALwESAIcBowCvAKQApQC0AHkAAgAUAI0BtgC3AAQAdAAMAAUAjgGQAJEACQCPAZgAmQALAAwADQAvAQ8AkAERAC8BEgCRARQAkgEWAJMBGADAAAQAFQAMAAUAlAGQAJEAlQDCAAkAlQGaAMQADQCfAA8AlgERAJ8AEgCXAaQApQAUAJgBFgCXAcgAfAADAAUAFQEJAJkBDwCaAcgAf'
..'AADAAUAmwEJAJwBDwCdAcgAfAADAAUA+AAJAAABDwCeAcgAfAADAAUAZAEJAGwBDwCfAcgAfAADAAUAoAEJAKEBDwCiAcgAfAADAAUAowEJAKQBDwClAcgAfAADAAUApgEJAKcBDwCoAcgAfAADAAUAqQEJAKoBDwCrAcwAfAADAAUAjgGnABYBqQCZAaYAfAABAKcArAGOABUACAAFAK0B'
..'kACRAAkArgENAJ8ADwCvAREAnwASALABpAClAMgAhwABAAUAEgEBABUAAgAFALEBAgCyAY4AiQALAAUArgCQAJEAlACvAAkAswGYAJkADQAvAQ8AtAERAC8BEgCHAaMArwCkAKUAtACKAAIAFAC1AbYAtwCOAIkAEgAFAI8AkACRAJIAkwCUAJMAlQCWAAkAtgGYAJkAmgCbAJwAkwCdAJM'
..'ACwCeAA0AnwAPALcBoQCTABEAnwASAIcBowCTAKQApQCmAIwAAgCnAIgBqQCJAaYAjAACAKcAiAGpAIgBpgCMAAIApwCIAakAuAEEAIkADAAFALkBkACRAAkAugGYAJkACwAMAA0ALwEPALsBEQAvARIAvAEUAL0BFgC+ARgAwAABABUAAgAFAL8BAgDAAY4AkQASAAUAjwCQAJEAkgCTAJ'
..'QAkwCVAJYACQBvAZgAmQCaAJsAnACTAJ0AkwALAJ4ADQCfAA8AcAGhAJMAEQCfABIAwQGjAJMApAClAKYAkgACAKcAwgGpAMIBpgCSAAIApwDCAakAwwGmAJIAAgCnAMIBqQDEAY4AkQALAAUArgCQAJEAlACvAAkAxQGYAJkADQDGAQ8AxwERAC8BEgDBAaMArwCkAKUAtACWAAIAFADIA'
..'bYAtwAEAJEADAAFAMkBkACRAAkAygGYAJkACwAMAA0AxgEPAMsBEQAvARIAzAEUAM0BFgDOARgAwAABABUAAgAFAM8BAgDQAY4AmQASAAUAjwCQAJEAkgCTAJQAkwCVAJYACQDRAZgAmQCaAJsAnACTAJ0AkwALAJ4ADQCfAA8A0gGhAJMAEQCfABIA0wGjAJMApAClAKYAmgACAKcA1AGp'
..'ANQBpgCaAAIApwDUAakA1QGmAJoAAgCnANQBqQDWAY4AmQALAAUArgCQAJEAlACvAAkA1wGYAJkADQDYAQ8A2QERANoBEgDbAaMArwCkAKUAtACeAAIAFADcAbYAtwAEAJkADAAFAN0BkACRAAkA3gGYAJkACwAMAA0A3wEPAOABEQDhARIA4gEUAOMBFgDkARgAwACOABUADAAFAOUBkAC'
..'RAJQArwCVAMIACQDmAZoAxAANAJ8ADwDnAREAnwASAOgBowCvAKQA6QG0AKEAAQDqAesByAChAAQABQDsAQkA7QENAO4BDwDvAcgAoQAEAAUA8AEJAPEBDQDuAQ8A8gHIAKEABAAFAPMBCQD0AQ0A7gEPAPUByAChAAQABQD2AQkA9AENAO4BDwD1AcgAoQAEAAUA9wEJAPgBDQDuAQ8A+Q'
..'HIAKEAAwAFAJsBCQD6AQ8A+wH8AaEAAwAFAP0B/gH/AaQApQDMAKEAAwAFAAACpwCcAakA+gEBAqEABQAFAAICAwIEAgUCtwAGAgcCCAIJAgECoQAFAAUACgIDAgQCBQK3AAYCCwIIAgkCAQKhAAYABQAMAg0CCAADAgQCBQK3AAYCDgIIAq8AAQKhAAUABQAPAgMCBAIFArcABgIQAggCC'
..'QIBAqEABQAFABECAwIEAgUCtwAGAhICCAIJAgECoQAFAAUAEwIDAgQCBQK3AAYCFAIIAgkCAQKhAAcABQAVAg0CCAAWAhcCAwIEAgUCtwAGAhgCCAIJAgECoQAHAAUAGQINAggAFgIaAgMCBAIFArcABgIbAggCCQIBAqEABgAFABwCDQIIAAMCBAIFArcABgIYAggCCQIBAqEABwAFABkC'
..'DQIIABYCGgIDAgQCBQK3AAYCGwIIAgkCAQKhAAUABQAPAgMCBAIFArcABgIQAggCCQIBAqEABQAFAAoCAwIEAgUCtwAGAgsCCAIJAgECoQAHAAUAFQINAggAFgIXAgMCBAIFArcABgIYAggCCQIBAqEABgAFAAwCDQIIAAMCBAIFArcABgIOAggCCQIBAqEABQAFABMCAwIEAgUCtwAGAhQ'
..'CCAIJAgECoQAGAAUAHAINAggAAwIEAgUCtwAGAhgCCAIJAgECoQAFAAUAEQIDAgQCBQK3AAYCEgIIAgkCAQKhAAUABQACAgMCBAIFArcABgIHAggCCQKmAKEAAAAdAhUAAgAeAh8CIAKlACECvgAAAAEAFQACAAUAIgICACMCjgDAABIABQCPAJAAkQCSAJMAlACTAJUAlgAJAEEBmACZAJ'
..'oAmwCcAJMAnQCTAAsAngANAJ8ADwBCAaEAkwARAJ8AEgAkAqMAkwCkAKUApgDBAAIApwArAakAKwGmAMEAAgCnACsBqQAlAqYAwQACAKcAKwGpACYCjgDAAAsABQCuAJAAkQCUAK8ACQAnApgAmQANAC8BDwAoAhEALwESACQCowCvAKQApQC0AMUAAgAUACkCtgC3AAQAwAAMAAUAKgKQA'
..'JEACQArApgAmQALAAwADQAvAQ8ALAIRAC8BEgAtAhQALgIWAC8CGADAAAEAFQACAAUAMAICADECjgDIABIABQCPAJAAkQCSAJMAlACTAJUAlgAJAOYBmACZAJoAmwCcAJMAnQCTAAsAngANAJ8ADwDnAaEAkwARAJ8AEgCHAaMAkwCkAKUApgDJAAIApwCIAakAiAGmAMkAAgCnAIgBqQAy'
..'AqYAyQACAKcAiAGpADMCjgDIAAsABQCuAJAAkQCUAK8ACQA0ApgAmQANAJ8ADwA1AhEAnwASAIcBowCvAKQApQD8Ac0AAQD+ATYCtADNAAEA6gHrAQQAyAAMAAUA5QGQAJEACQA3ApgAmQALAAwADQAvAQ8AOAIRAC8BEgA5AhQAOgIWADsCGADAADwC0AAAAAEAFQACAAUAPQICAD4CjgD'
..'SABIABQCPAJAAkQCSAJMAlACTAJUAlgAJAMMAmACZAJoAmwCcAJMAnQCTAAsAngANAJ8ADwDFAKEAkwARAJ8AEgCiAKMAkwCkAKUApgDTAAIApwA/AqkAPwKmANMAAgCnAD8CqQBAAqYA0wACAKcAPwKpAEECjgDSAAsABQCuAJAAkQCUAK8ACQBCApgAmQANALEADwBDAhEAswASAKIAow'
..'CvAKQApQC0ANcAAgAUAEQCtgC3AAQA0gAMAAUARQKQAJEACQBGApgAmQALAAwADQC6AA8ARwIRALwAEgBIAhQASQIWAEoCGADAAAEAFQACAAUASwICAEwCjgDaABIABQCPAJAAkQCSAJMAlACTAJUAlgAJANAAmACZAJoAmwCcAJMAnQCTAAsAngANAJ8ADwDRAKEAkwARAJ8AEgAkAqMAk'
..'wCkAKUApgDbAAIApwBNAqkATQKmANsAAgCnAE0CqQBOAqYA2wACAKcATQKpAE8CjgDaAAsABQCuAJAAkQCUAK8ACQBQApgAmQANAC8BDwBRAhEALwESACQCowCvAKQApQC0AN8AAgAUAFICtgC3AAQA2gAMAAUAUwKQAJEACQBUApgAmQALAAwADQAvAQ8AVQIRAC8BEgBWAhQAVwIWAFgC'
..'GADAAAEAFQACAAUAWQICAFoCjgDiABIABQCPAJAAkQCSAJMAlACTAJUAlgAJAN4AmACZAJoAmwCcAJMAnQCTAAsAngANAJ8ADwDfAKEAkwARAJ8AEgAqAaMAkwCkAKUApgDjAAIApwBNAqkATQKmAOMAAgCnAE0CqQBbAqYA4wACAKcATQKpAFwCjgDiAAsABQCuAJAAkQCUAK8ACQBdApg'
..'AmQANAC8BDwBeAhEALwESACoBowCvAKQApQC0AOcAAgAUAF8CtgC3AAQA4gAMAAUAYAKQAJEACQBhApgAmQALAAwADQAvAQ8AYgIRAC8BEgBjAhQAZAIWAGUCGADAAAEAFQACAAUAZgICAGcCjgDqAAsABQCuAJAAkQCUAK8ACQBoApgAmQANALEADwBpAhEAswASAHkBowCvAKQApQC0AO'
..'sAAgAUAGoCtgC3AI4A6gASAAUAjwCQAJEAkgCTAJQAkwCVAJYACQDpAJgAmQCaAJsAnACTAJ0AkwALAJ4ADQCfAA8A6gChAJMAEQCfABIAeQGjAJMApAClAKYA7QACAKcAPwKpAGsCpgDtAAIApwA/AqkAPwKmAO0AAgCnAD8CqQBsAgQA6gAMAAUAbQKQAJEACQBuApgAmQALAAwADQC6A'
..'A8AbwIRALwAEgBwAhQAcQIWAHICGADAAAEAFQACAAUAcwICAHQCjgDyABIABQCPAJAAkQCSAJMAlACTAJUAlgAJAHUCmACZAJoAmwCcAJMAnQCTAAsAngANAJ8ADwB2AqEAkwARAJ8AEgDbAaMAkwCkAKUApgDzAAIApwB3AqkAdwKmAPMAAgCnAHcCqQB4AqYA8wACAKcAdwKpAHkCjgDy'
..'AAsABQCuAJAAkQCUAK8ACQB6ApgAmQANANgBDwB7AhEA2gESANMBowCvAKQApQC0APcAAgAUAHwCtgC3AAQA8gAMAAUAfQKQAJEACQB+ApgAmQALAAwADQDfAQ8AfwIRAOEBEgCAAhQAgQIWAIICGADAAAEAFQACAAUAgwICAIQCjgD6ABIABQCPAJAAkQCSAJMAlACTAJUAlgAJAAMBmAC'
..'ZAJoAmwCcAJMAnQCTAAsAngANAJ8ADwAEAaEAkwARAJ8AEgDBAaMAkwCkAKUApgD7AAIApwDCAakAwgGmAPsAAgCnAMIBqQDDAaYA+wACAKcAwgGpAIUCjgD6AAsABQCuAJAAkQCUAK8ACQCGApgAmQANAMYBDwCHAhEALwESAMEBowCvAKQApQC0AP8AAgAUAIgCtgC3AAQA+gAMAAUAiQ'
..'KQAJEACQCKApgAmQALAAwADQDGAQ8AiwIRAC8BEgCMAhQAjQIWAI4CGADAAAEAAAACAAUAjwICAJACjgACAQsAlACvAJUAkQIJAJICmgCTAgsAngANAJQCDwCVAhEAlAISAJYCowCvAJcCmAKOAAIBCwCUAK8AlQCRAgkAmQKaAJMCCwCeAA0AlAIPAJoCEQCUAhIAlgKjAK8AlwKYAo4AA'
..'gELAJQArwCVAJECCQCbApoAkwILAJ4ADQCcAg8AnQIRAJ4CEgCWAqMArwCXApgCjgACAQsAlACvAJUAkQIJAJ8CmgCTAgsAngANAJQCDwCgAhEAlAISAJYCowCvAJcCmAKOAAIBCwCUAK8AlQCRAgkAoQKaAJMCCwCeAA0AnAIPAKICEQCeAhIAlgKjAK8AlwKYAo4AAgELAJQArwCVAJEC'
..'CQCjApoAkwILAJ4ADQCUAg8ApAIRAJQCEgCWAqMArwCXApgCjgACAQsAlACvAJUAkQIJAKUCmgCTAgsAngANAJwCDwCmAhEAngISAJYCowCvAJcCmAKOAAIBCwCUAK8AlQCRAgkApwKaAJMCCwCeAA0AqAIPAKkCEQCqAhIAlgKjAK8AlwKYAo4AAgELAJQArwCVAJECCQCrApoAkwILAJ4'
..'ADQCUAg8ArAIRAJQCEgCWAqMArwCXApgCjgACAQsAlACvAJUAkQIJAK0CmgCTAgsAngANAJQCDwCuAhEAlAISAJYCowCvAJcCmAKOAAIBCwCUAK8AlQCRAgkArwKaAJMCCwCeAA0AnAIPALACEQCeAhIAlgKjAK8AlwKYAo4AAgELAJQArwCVAJECCQCxApoAkwILAJ4ADQCoAg8AsgIRAK'
..'oCEgCWAqMArwCXApgCjgACAQsAlACvAJUAkQIJALMCmgCTAgsAngANAJwCDwC0AhEAngISAJYCowCvAJcCmAKOAAIBCQAHAAgAlACTAJUAtQIJALYCmgC3AgsAngAPALgCEgC5AqMAkwCOAAIBCwCUAK8AlQCRAgkAugKaAJMCCwCeAA0AqAIPALsCEQCqAhIAlgKjAK8AlwKYAo4AAgELA'
..'JQArwCVAJECCQC8ApoAkwILAJ4ADQCUAg8AvQIRAJQCEgCWAqMArwCXApgCjgACAQsAlACvAJUAkQIJAL4CmgCTAgsAngANAJQCDwC/AhEAlAISAJYCowCvAJcCmAKOAAIBCwCUAK8AlQCRAgkAwAKaAJMCCwCeAA0AnAIPAMECEQCeAhIAlgKjAK8AlwKYAo4AAgELAJQArwCVAJECCQDC'
..'ApoAkwILAJ4ADQCoAg8AwwIRAKoCEgCWAqMArwCXApgCjgACAQsAlACvAJUAkQIJAMQCmgCTAgsAngANAKgCDwDFAhEAqgISAJYCowCvAJcCmAKOAAIBCwCUAK8AlQCRAgkAxgKaAJMCCwCeAA0AxwIPAMgCEQDJAhIAlgKjAK8AlwKYAo4AAgELAJQArwCVAJECCQDKApoAkwILAJ4ADQC'
..'oAg8AywIRAKoCEgCWAqMArwCXApgCjgACAQsAlACvAJUAkQIJAMwCmgCTAgsAngANAJwCDwDNAhEAngISAJYCowCvAJcCmAKOAAIBCwCUAK8AlQCRAgkAzgKaAJMCCwCeAA0AqAIPAM8CEQCqAhIAlgKjAK8AlwKYAo4AAgELAJQArwCVAJECCQDQApoAkwILAJ4ADQCcAg8A0QIRAJ4CEg'
..'CWAqMArwCXApgC0gJAAgCOANcC2AIvAUADQAQA2QLaAtsCnwAAjgDcAt0CLwEAjgDeAt8CLwFABgDZAtoC4ALhAgCOAOIC4wIvAQDZAtoC5AIvAQCOAOUC5gIvAUADgI4A5wLoAi8BAI4A6QLqAi8BgI4A6wLsAi8BQAIAjgDtAu4CLwGAjgDvAvACLwEAjgDxAvICLwEA2QLpAvMCLwECA'
..'QkABQDTAgcACAAJANQCmgCTAgsAngANAC8BDwDVAhEALwESANYC0gJAAgCOANcC9gKfAEADQAQA2QLaAvcCLwEAjgDcAvgCnwAAjgDeAvkCnwBABgDZAtoC+gL7AgCOAOIC/AKfAADZAtoC/QKfAACOAOUC/gKfAEADgI4A5wL/Ap8AAI4A6QIAA58AgI4A6wIBA58AQAIAjgDtAgIDnwCA'
..'jgDvAgMDnwAAjgDxAgQDnwAA2QLpAgUDnwACAQkABQDTAgcACAAJAPQCmgCTAgsAngANAJ8ADwD1AhEAnwASANYC0gJAAgCOANcCCgMHA0ADQAQA2QLaAgsDDAMAjgDcAg0DBwMAjgDeAg4DBwNABgDZAtoCDwMQAwCOAOICEQMHAwDZAtoCEgMHAwCOAOUCEwMHA0ADgI4A5wIUAwcDAI4'
..'A6QIVAwcDgI4A6wIWAwcDQAIAjgDtAhcDBwOAjgDvAhgDBwMAjgDxAhkDBwMA2QLpAhoDBwMCAQkABQDTAgcACAAJAAYDmgCTAgsAngANAAcDDwAIAxEACQMSANYC0gJAAgCOANcCHQMMA0ADQAQA2QLaAh4DBwMAjgDcAh8DDAMAjgDeAiADDANABgDZAtoCIQMiAwCOAOICIwMMAwDZAt'
..'oCJAMMAwCOAOUCJQMMA0ADgI4A5wImAwwDAI4A6QInAwwDgI4A6wIoAwwDQAIAjgDtAikDDAOAjgDvAioDDAMAjgDxAisDDAMA2QLpAiwDDAMCAQcABQDTAgcACAAJABsDmgCTAgsAngAPABwDEgDWAi0DAgEBAAUALgMtAwIBAQAFAC8DAQAAAAIABQAwAwIAMgOOACIBCAAHAAgACQAyA'
..'5gAmQALAJ4ADQAzAw8ANAMRADUDEgA2A8gAIwEDAAUANwMJADgDDQA5AzoDJAECADsDPAM9AzwDPgMkAQsABQA/A5oAQANBA0IDQwOlAEQDCABFA6UARgNHAxIASANJA0oD/gFLA6QATAO0ACMBBADqAU0DFABOA08DUAO2ALcApgAjAQIApwBRA6kAUgOOACIBDQAFAFMDBwAIAJQArwCV'
..'AFQDCQBVA5oAVgOcAJgCCwCeAA0AVwMPAFgDEQBZAxIAWgOjAK8AWwMpAQIABQCmAKkAXAO0ACkBBABdA14D6gFfAxQAYAO2ALcAmQAYAKoAFwAYAKsAFwAZAKoAFwAZAKsAGwAaAKoAFwAaAKsAHQAgAKoALAAgAKsAHgAhAKoAHgAhAKsA0wAlAKoAJwAlAKsAIgAmAKoAIgAmAKsA2wA'
..'qAKoAMQAqAKsAJwArAKoAJwArAKsA4wAvAKoANwAvAKsALAAwAKoALAAwAKsA7QA1AKoAfAA1AKsAMQA2AKoAMQA2AKsA8wA6AKoAPAA6AKsANwA7AKoANwA7AKsA+wBEAKoAhwBEAKsAPABFAKoAPABFAKsAdQBIAKoARwBIAKsARwBJAKoARwBJAKsASwBKAKoARwBKAKsATQBQAKoAXA'
..'BQAKsATgBRAKoATgBRAKsAFwBVAKoAVwBVAKsAUgBWAKoAUgBWAKsAwQBaAKoAYQBaAKsAVwBbAKoAVwBbAKsARwBfAKoAZwBfAKsAXABgAKoAXABgAKsAbQBlAKoAfABlAKsAYQBmAKoAYQBmAKsAmgBqAKoAPABqAKsAZwBrAKoAZwBrAKsAkgBuAKoAbQBuAKsAbQBvAKoAbQBvAKsAc'
..'QBwAKoAbQBwAKsAcwB2AKoAdQB2AKsAdQB3AKoAdQB3AKsAeQB4AKoAdQB4AKsAewCFAKoAPACFAKsAfACGAKoAfACGAKsAjACNAKoAjACNAKsAigCOAKoAjACOAKsAjACPAKoAjACPAKsAkACTAKoAkgCTAKsAkgCUAKoAkgCUAKsAlgCVAKoAkgCVAKsAmACbAKoAmgCbAKsAmgCcAKoA'
..'mgCcAKsAngCdAKoAmgCdAKsAoACqAKoAfACqAKsAoQC9AKoAoQC9AKsAyQDCAKoAwQDCAKsAwQDDAKoAwQDDAKsAxQDEAKoAwQDEAKsAxwDKAKoAyQDKAKsAyQDLAKoAyQDLAKsAzQDMAKoAyQDMAKsA0ADUAKoA0wDUAKsA0wDVAKoA0wDVAKsA1wDWAKoA0wDWAKsA2QDcAKoA2wDcAKs'
..'A2wDdAKoA2wDdAKsA3wDeAKoA2wDeAKsA4QDkAKoA4wDkAKsA4wDlAKoA4wDlAKsA5wDmAKoA4wDmAKsA6QDuAKoA7QDuAKsA6wDvAKoA7QDvAKsA7QDwAKoA7QDwAKsA8QD0AKoA8wD0AKsA8wD1AKoA8wD1AKsA9wD2AKoA8wD2AKsA+QD8AKoA+wD8AKsA+wD9AKoA+wD9AKsA/wD+AK'
..'oA+wD+AKsAAQEiATEDIwEoAaoAIwEoAasAKQE=')
for _,obj in pairs(Objects) do
	obj.Parent = script
end

RunScripts()
